name: Gus Bonfant
description: Software Engineer
meta_description: "I'm Gus Bonfant: A programmer, foodie, diver, and design enthusiast."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://gbonfant.com'

# Details for the RSS feed generator
url: 'http://gbonfant.com'
author: 'Gus Bonfant'

sass:
  style: :compressed
