# Site settings
title: Gus Bonfant
description: >
  Gus Bonfant. Software Engineer, foodie, diver and design enthusiast.
baseurl: ""
url: "http://gbonfant.com"
twitter_username: gbonfant
github_username:  gbonfant
permalink: blog/:title

# Build settings
markdown: redcarpet
sass:
  style: :compressed
