# Site settings
title: Gus Bonfante
description: >
  Gus Bonfante. Software Engineer, foodie, diver and design enthusiast.
baseurl: ""
url: "http://gbonfant.com"
twitter_username: gbonfant
github_username:  gbonfant
permalink: blog/:title

# Build settings
markdown: kramdown
sass:
  style: :compressed
