# Site settings
title: Gus Bonfant
email: your-email@domain.com
description: "Gus Bonfant. Software engineer. Obsessively curious."
baseurl: ""
url: "http://gbonfant.com"

# Build settings
markdown: kramdown
permalink: pretty
